services:
  # service 1: mongo

  mongo:
    container_name: mongodb-container
    image: mongo:latest
    ports:
      # Note: 27018 is exposed to client (as most of the time i have multiple connection opened at time,)
      - 27018:27017
    volumes:
      - mongoData:/data/db
  # service 2: backend

  backend:
    image: 'dev-tools-studio-backend:v1.0.0'
    container_name: dev-tools-studio-backend-dev-container
    build:
      context: '.'
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - './src/config/environment/dev.env'
    environment:
      MONGO_SERVICE_NAME: 'mongodb://mongo:27017'
    depends_on:
      - mongo
    develop:
      watch:
        - action: sync+restart
          path: ./
          target: /dev-tools-studio-backend
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    # expose:
    #   - 3000
    # command: npm run dev

volumes:
  mongoData:
