FROM node:22-alpine

WORKDIR /usr/src/app

COPY package*.json .

RUN npm install
COPY . .

# Build & Clean up unnecessary files
RUN npm run build && \
    rm -rf src && \
    rm -rf package-lock.json

EXPOSE 3000

CMD [ "npm", "run", "start" ]
