services:
  backend:
    image: 'wasitshafi700/dev-tools-studio-backend:latest'
    container_name: backend
    build:
      context: '.'
      dockerfile: Dockerfile.prod
    ports:
      - 3000:3000
    env_file:
      - './src/config/environment/prod.env'
