services:
  mongo:
    container_name: dts_dev_mongo_container
    image: mongo:latest
    ports:
      # NOTE(WASIT): 27018 is exposed to client (Most of the time I have multiple connections opened simultaneously)
      - 27018:27017
    volumes:
      - mongoData:/data/db

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6397

  redis_insight:
    image: redis/redisinsight:latest
    container_name: dts_dev_redis_insight_container
    ports:
      - 5540:5540

  backend:
    image: 'wasitshafi700/dev-tools-studio:latest'
    container_name: dts_dev_express_container
    build:
      context: '.'
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - './src/config/environment/dev.env'
    environment:
      MONGO_SERVICE_NAME: 'mongodb://mongo:27017'
      REDIS_SERVICE_NAME: 'redis'
    depends_on:
      - redis
      - mongo
    develop:
      watch:
        - action: sync+restart
          path: ./
          target: /usr/src/app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    # expose:
    #   - 3000
    # command: npm run dev

volumes:
  mongoData:
