services:
  backend:
    image: 'dev-tools-studio-backend:v1.0.0'
    container_name: dev-tools-studio-backend-prod-container
    build:
      context: '.'
      dockerfile: Dockerfile.prod
    ports:
      - 3000:3000
    env_file:
      - './src/config/environment/prod.env'
