openapi: 3.1.0
info:
  title: Dev Tools Studio
  description: Backend API docs for the project **Dev Tools Studio**, for more info checkout github repo [https://github.com/wasit-shafi/dev-tools-studio-backend](https://github.com/wasit-shafi/dev-tools-studio-backend) or postman API Collection [https://www.postman.com/wasit-shafi-wani/dev-tools-studio/overview](https://www.postman.com/wasit-shafi-wani/dev-tools-studio/overview)
  termsOfService: https://swagger.io/terms/
  contact:
    email: wasitshafi700@gmail.com
  version: 1.0.0
servers:
  - url: http://localhost:3000/api/v1
  - url: http://localhost:3000/api/v2
  - url: http://localhost:3000
paths:
  /:
    get:
      responses:
        '200':
          description: Get api / response
  /say-hello:
    get:
      responses:
        '200':
          description: Get api /say-hello response
