name: CD_PIPELINE

on:
  workflow_run:
    workflows:
      - CI_PIPELINE
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull latest image from Docker Hub
        run: sudo docker pull wasitshafi700/dev-tools-studio-backend:latest

      - name: Remove existing docker container
        run: sudo docker rm -f dts-backend

      # # TODO(Wasit): start container via docker compose (temporary blocked due to prod env file)
      # - name: Run docker container
      #   run: docker-compose -f docker-compose.prod.yml up --build -V

      - name: Run docker container
        env:
          ACCESS_TOKEN_EXPIRY: ${{secrets.ACCESS_TOKEN_EXPIRY}}
          ACCESS_TOKEN_SECRET: ${{secrets.ACCESS_TOKEN_SECRET}}
          API_RATE_LIMITER_IP_WHITELIST: ${{secrets.API_RATE_LIMITER_IP_WHITELIST}}
          API_RATE_LIMITER_THRESHOLD_LIMIT: ${{secrets.API_RATE_LIMITER_THRESHOLD_LIMIT}}
          API_RATE_LIMITER_THRESHOLD_LIMIT_STRICT: ${{secrets.API_RATE_LIMITER_THRESHOLD_LIMIT_STRICT}}
          API_RATE_LIMITER_WINDOW_IN_MINUTE: ${{secrets.API_RATE_LIMITER_WINDOW_IN_MINUTE}}
          API_RATE_LIMITER_WINDOW_IN_MINUTE_STRICT: ${{secrets.API_RATE_LIMITER_WINDOW_IN_MINUTE_STRICT}}
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_PRESIGNED_URL_EXPIRY: ${{secrets.AWS_PRESIGNED_URL_EXPIRY}}
          AWS_S3_BUCKET_NAME: ${{secrets.AWS_S3_BUCKET_NAME}}
          AWS_S3_BUCKET_REGION: ${{secrets.AWS_S3_BUCKET_REGION}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_SNS_REGION: ${{secrets.AWS_SNS_REGION}}
          CORS_ORIGIN: ${{secrets.CORS_ORIGIN}}
          DATABASE_URI: ${{secrets.DATABASE_URI}}
          EMAIL_SERVICE_SENDER_EMAIL_ID: ${{secrets.EMAIL_SERVICE_SENDER_EMAIL_ID}}
          EMAIL_SERVICE_SENDER_NAME: ${{secrets.EMAIL_SERVICE_SENDER_NAME}}
          EMAIL_SERVICE_SMTP_HOST_SERVER: ${{secrets.EMAIL_SERVICE_SMTP_HOST_SERVER}}
          EMAIL_SERVICE_SMTP_PASSWORD: ${{secrets.EMAIL_SERVICE_SMTP_PASSWORD}}
          EMAIL_SERVICE_SMTP_PORT: ${{secrets.EMAIL_SERVICE_SMTP_PORT}}
          EMAIL_SERVICE_SMTP_USER: ${{secrets.EMAIL_SERVICE_SMTP_USER}}
          EXPRESS_PORT: ${{secrets.EXPRESS_PORT}}
          FE_BASE_URL: ${{secrets.FE_BASE_URL}}
          GEOAPIFY_API_KEY: ${{secrets.GEOAPIFY_API_KEY}}
          IP_INFO_ACCESS_TOKEN: ${{secrets.IP_INFO_ACCESS_TOKEN}}
          NODE_ENV: ${{secrets.NODE_ENV}}
          RECAPTCHA_SECRET_KEY: ${{secrets.RECAPTCHA_SECRET_KEY}}
          REDIS_HOST: ${{secrets.REDIS_HOST}}
          REDIS_PORT: ${{secrets.REDIS_PORT}}
          REDIS_USER_PASSWORD: ${{secrets.REDIS_USER_PASSWORD}}
          REFRESH_TOKEN_EXPIRY: ${{secrets.REFRESH_TOKEN_EXPIRY}}
          REFRESH_TOKEN_SECRET: ${{secrets.REFRESH_TOKEN_SECRET}}
          SALT_ROUNDS: ${{secrets.SALT_ROUNDS}}
        run: >
          docker run -d -p 3000:3000
          -e ACCESS_TOKEN_EXPIRY=$ACCESS_TOKEN_EXPIRY
          -e ACCESS_TOKEN_SECRET=$ACCESS_TOKEN_SECRET
          -e API_RATE_LIMITER_IP_WHITELIST=$API_RATE_LIMITER_IP_WHITELIST
          -e API_RATE_LIMITER_THRESHOLD_LIMIT=$API_RATE_LIMITER_THRESHOLD_LIMIT
          -e API_RATE_LIMITER_THRESHOLD_LIMIT_STRICT=$API_RATE_LIMITER_THRESHOLD_LIMIT_STRICT
          -e API_RATE_LIMITER_WINDOW_IN_MINUTE=$API_RATE_LIMITER_WINDOW_IN_MINUTE
          -e API_RATE_LIMITER_WINDOW_IN_MINUTE_STRICT=$API_RATE_LIMITER_WINDOW_IN_MINUTE_STRICT
          -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
          -e AWS_PRESIGNED_URL_EXPIRY=$AWS_PRESIGNED_URL_EXPIRY
          -e AWS_S3_BUCKET_NAME=$AWS_S3_BUCKET_NAME
          -e AWS_S3_BUCKET_REGION=$AWS_S3_BUCKET_REGION
          -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
          -e AWS_SNS_REGION=$AWS_SNS_REGION
          -e CORS_ORIGIN=$CORS_ORIGIN
          -e DATABASE_URI=$DATABASE_URI
          -e EMAIL_SERVICE_SENDER_EMAIL_ID=$EMAIL_SERVICE_SENDER_EMAIL_ID
          -e EMAIL_SERVICE_SENDER_NAME=$EMAIL_SERVICE_SENDER_NAME
          -e EMAIL_SERVICE_SMTP_HOST_SERVER=$EMAIL_SERVICE_SMTP_HOST_SERVER
          -e EMAIL_SERVICE_SMTP_PASSWORD=$EMAIL_SERVICE_SMTP_PASSWORD
          -e EMAIL_SERVICE_SMTP_PORT=$EMAIL_SERVICE_SMTP_PORT
          -e EMAIL_SERVICE_SMTP_USER=$EMAIL_SERVICE_SMTP_USER
          -e EXPRESS_PORT=$EXPRESS_PORT
          -e FE_BASE_URL=$FE_BASE_URL
          -e GEOAPIFY_API_KEY=$GEOAPIFY_API_KEY
          -e IP_INFO_ACCESS_TOKEN=$IP_INFO_ACCESS_TOKEN
          -e NODE_ENV=$NODE_ENV
          -e RECAPTCHA_SECRET_KEY=$RECAPTCHA_SECRET_KEY
          -e REDIS_HOST=$REDIS_HOST
          -e REDIS_PORT=$REDIS_PORT
          -e REDIS_USER_PASSWORD=$REDIS_USER_PASSWORD
          -e REFRESH_TOKEN_EXPIRY=$REFRESH_TOKEN_EXPIRY
          -e REFRESH_TOKEN_SECRET=$REFRESH_TOKEN_SECRET
          -e SALT_ROUNDS=$SALT_ROUNDS
          --name dts-backend wasitshafi700/dev-tools-studio-backend;

      - name: Remove all unused/dangling images
        run: sudo docker image prune -f
