name: CD_PIPELINE

on:
  workflow_run:
    workflows:
      - CI_PIPELINE
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull latest image from DockerHub
        run: sudo docker pull wasitshafi700/dev-tools-studio-backend:latest

      - name: Remove existing docker container
        run: sudo docker rm -f wasitshafi700/dev-tools-studio-backend

      # # TODO(Wasit): start container via docker compose (temporary blocked due to prod env file)
      # - name: Run docker container
      #   run: docker-compose -f docker-compose.prod.yml up --build -V
