name: CI_PIPELINE

on:
  push:
    branches: ['dev']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Logging into DockerHub
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Building New Docker Image
        run: docker build . -t wasitshafi700/dev-tools-studio:latest --file Dockerfile.prod

      - name: Push Image on DockerHub
        run: docker push wasitshafi700/dev-tools-studio:latest
